[package]
name = "ayiah"
version = "0.1.0"
categories = []
description = ""
edition = "2024"
rust-version = "1.85.0"
homepage = "https://github.com/Ns2Kracy/Ayiah"
keywords = []
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ns2Kracy/Ayiah"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.87"
axum = { version = "0.8.1", features = ["multipart", "ws"] }
axum-extra = { version = "0.10.0", features = [
    "cookie",
    "multipart",
    "typed-header",
    "typed-routing",
] }
bcrypt = "0.17.0"
bytes = "1.5.0"
chrono = "0.4.40"
comrak = { version = "0.36.0", default-features = false, features = [
    "bon",
    "shell-words",
    "syntect",
    "xdg",
] }
config = "0.15.11"
dashmap = "6.1.0"
data-encoding = "2.8.0"
dirs = "6.0.0"
epub = "2.1.2"
fastwebsockets = { version = "0.10.0", features = ["upgrade", "with_axum"] }
futures = "0.3.31"
futures-core = "0.3.31"
futures-util = "0.3.31"
glidesort = "0.1.2"
hyper = { version = "1.6.0", features = ["full"] }
image = "0.25.5"
infer = "0.19.0"
jsonwebtoken = "9.3.1"
notify = "8.0.0"
num_cpus = "1.16.0"
once_cell = "1.21.1"
parking_lot = "0.12.1"
pdf = "0.9.0"
rand = "0.9.0"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["json"] }
ring = "0.17.14"
sea-orm = { version = "1.1.7", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
sea-orm-migration = { version = "1.1.7", features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
symphonia = { version = "0.5.4", features = [
    "all",
    "mpa",
    "opt-simd",
    "opt-simd-avx",
    "opt-simd-neon",
    "opt-simd-sse",
    "symphonia-bundle-mp3",
    "symphonia-format-riff",
] }
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
toml = "0.8.20"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "json",
    "chrono",
] }
utoipa = { version = "5.3.1", features = [
    "axum_extras",
    "openapi_extensions",
    "chrono",
    "time",
    "uuid",
] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
uuid = { version = "1.16.0", features = ["v4"] }
validator = { version = "0.20.0", features = ["derive"] }
walkdir = "2.5.0"
webp = "0.3.0"
zip = "2.4.2"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
strip = true
codegen-units = 1
