[package]
name = "ayiah-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
async-trait = "0.1.77"
tokio = { version = "1.36.0", features = ["full"] }
